### ISSUE TITLE
Error for new version 5.5.4

### ISSUE THREAD

**Issue by dieend** [sous-chefs/mysql#243]
The error log:

```
[2014-10-08T04:13:38+00:00] INFO: Processing mysql_service[default] action create (mysql::server line 20)
==> app: 
==> app: ================================================================================
==> app: Error executing action `create` on resource 'mysql_service[default]'
==> app: ================================================================================
==> app: 
==> app: 
==> app: NoMethodError
==> app: -------------
==> app: No resource or method named `execute' for `Chef::Provider::MysqlService::Ubuntu "none"'
==> app: 
==> app: 
==> app: Cookbook Trace:
==> app: ---------------
==> app: 
==> app: /var/vagrant-chef/chef-solo-1/cookbooks/mysql/libraries/provider_mysql_service_ubuntu.rb:60:in `block in <class:Ubuntu>'
==> app: 
==> app: 
==> app: Resource Declaration:
==> app: ---------------------
==> app: # In /var/vagrant-chef/chef-solo-1/cookbooks/mysql/recipes/server.rb
==> app: 
==> app:  20: mysql_service node['mysql']['service_name'] do
==> app:  21:   version node['mysql']['version']
==> app:  22:   port node['mysql']['port']
==> app:  23:   data_dir node['mysql']['data_dir']
==> app:  24:   server_root_password node['mysql']['server_root_password']
==> app:  25:   server_debian_password node['mysql']['server_debian_password']
==> app:  26:   server_repl_password node['mysql']['server_repl_password']
==> app:  27:   allow_remote_root node['mysql']['allow_remote_root']
==> app:  28:   remove_anonymous_users node['mysql']['remove_anonymous_users']
==> app:  29:   remove_test_database node['mysql']['remove_test_database']
==> app:  30:   root_network_acl node['mysql']['root_network_acl']
==> app:  31:   package_version node['mysql']['server_package_version']
==> app:  32:   package_action node['mysql']['server_package_action']
==> app:  33:   action :create
==> app:  34: end
==> app: 
==> app: 
==> app: 
==> app: Compiled Resource:
==> app: ------------------
==> app: # Declared in /var/vagrant-chef/chef-solo-1/cookbooks/mysql/recipes/server.rb:20:in `from_file'
==> app: 
==> app: mysql_service("default") do
==> app:   action [:create]
==> app:   retries 0
==> app:   retry_delay 2
==> app:   cookbook_name :mysql
==> app:   recipe_name "server"
==> app:   port "3306"
==> app:   data_dir "/var/lib/mysql"
==> app:   server_root_password "serverrootpassword"
==> app:   server_debian_password "gnuslashlinux4ev4r"
==> app:   remove_anonymous_users true
==> app:   remove_test_database true
==> app:   package_action "install"
==> app: end
==> app: 
==> app: 
==> app: 
==> app: [2014-10-08T04:13:38+00:00] INFO: Running queued delayed notifications before re-raising exception
==> app: [2014-10-08T04:13:38+00:00] ERROR: Running exception handlers
==> app: [2014-10-08T04:13:38+00:00] ERROR: Exception handlers complete
==> app: [2014-10-08T04:13:38+00:00] FATAL: Stacktrace dumped to /vagrant/.vagrant/file_cache_path/chef-stacktrace.out
==> app: [2014-10-08T04:13:38+00:00] ERROR: mysql_service[default] (mysql::server line 20) had an error: NoMethodError: No resource or method named `execute' for `Chef::Provider::MysqlService::Ubuntu "none"'
==> app: [2014-10-08T04:13:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

It's on vagrant box ubuntu/trusty64

**Comment by mexey89** [comment]
fix?

**Comment by phanikumar1210** [comment]
I am still facing the same error as specified above could anyone help me on this.
