### ISSUE TITLE
Reload action not applicable with systemd

### ISSUE THREAD

**Issue by klyonrad** [sous-chefs/mysql#459]
### Cookbook version

7.2.0

(but juding from the source code, this also applies to 8.0.1)
### Chef-client version

12.9.41
### Platform Details

ubuntu/16-04
### Scenario:

notify the service with `:reload` action after adding custom config files.
### Steps to Reproduce:
- setup `mysql_service 'default'` resource with `action [:create, :start]
- `notifies :reload, 'mysql_service[default]'` in another resource block
### Expected Result:

successfull execution of the mysql-default service reloading
### Actual Result:

The service cannot be reloaded and the execution of the cookbook fails.

Restarting the services works though.

```
           ================================================================================
           Error executing action `reload` on resource 'mysql_service[default]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           service[default :reload mysql-default] (/tmp/kitchen/cookbooks/mysql/libraries/provider_mysql_service_systemd.rb line 106) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3'
           ---- Begin output of /bin/systemctl --system reload mysql-default ----
           STDOUT: 
           STDERR: Failed to reload mysql-default.service: Job type reload is not applicable for unit mysql-default.service.
           See system logs and 'systemctl status mysql-default.service' for details.
           ---- End output of /bin/systemctl --system reload mysql-default ----
           Ran /bin/systemctl --system reload mysql-default returned 3
```
### Suspection

the `:reload` block in systemd service manager is missing a `supports :reload`

**Comment by bassrock** [comment]
hi @klyonrad  I am experiencing sort of the same issue. I intermittently get:

```
==> default: [2016-12-14T01:31:01+00:00] INFO: service[default :start mysql-default] enabled
==> default: 
==> default:       - enable service service[default :start mysql-default]
==> default:     * service[default :start mysql-default] action start
==> default:       
==> default:       ================================================================================
==> default:       Error executing action `start` on resource 'service[default :start mysql-default]'
==> default:       ================================================================================
==> default:       
==> default:       Mixlib::ShellOut::ShellCommandFailed
==> default:       ------------------------------------
==> default:       Expected process to exit with [0], but received '1'
==> default:       ---- Begin output of /bin/systemctl --system start mysql-default ----
==> default:       STDOUT: 
==> default:       STDERR: Job for mysql-default.service failed because the control process exited with error code. See "systemctl status mysql-default.service" and "journalctl -xe" for details.
==> default:       ---- End output of /bin/systemctl --system start mysql-default ----
==> default:       Ran /bin/systemctl --system start mysql-default returned 1
==> default:       
==> default:       Cookbook Trace:
==> default:       ---------------
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:       
==> default:       Resource Declaration:
==> default:       ---------------------
==> default:       # In /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_systemd.rb
==> default:       
==> default:        75:         service "#{new_resource.name} :start #{mysql_name}" do
==> default:        76:           service_name mysql_name
==> default:        77:           provider Chef::Provider::Service::Systemd
==> default:        78:           supports restart: true, status: true
==> default:        79:           action [:enable, :start]
==> default:        80:         end
==> default:        81:       end
==> default:       
==> default:       Compiled Resource:
==> default:       ------------------
==> default:       # Declared in /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_systemd.rb:75:in `block in <class:MysqlServiceSystemd>'
==> default:       
==> default:       service("default :start mysql-default") do
==> default:         provider Chef::Provider::Service::Systemd
==> default:         action [:enable, :start]
==> default:         updated true
==> default:         supports {:restart=>true, :status=>true}
==> default:         retries 0
==> default:         retry_delay 2
==> default:         default_guard_interpreter :default
==> default:         service_name "mysql-default"
==> default:         enabled true
==> default:         pattern "default :start mysql-default"
==> default:         declared_type :service
==> default:         cookbook_name "Vagrant"
==> default:       end
==> default:       
==> default:       Platform:
==> default:       ---------
==> default:       x86_64-linux
==> default:       
==> default: [2016-12-14T01:31:01+00:00] INFO: Running queued delayed notifications before re-raising exception
```

In my case it looks like the old service is not stopped before it is created. Have you found a solution for your issue?
