### ISSUE TITLE
mysql_service  - Cannot Change Provider 

### ISSUE THREAD

**Issue by darkn3rd** [sous-chefs/mysql#575]
### Cookbook version
`8.5.1`
### Chef-client version
`14.4.56`

### Platform Details

Test Kitchen auto-gens Dockerfile using Docker Image ubuntu:16.04

```Dockerfile
FROM ubuntu:16.04
RUN [ ! -f "/sbin/initctl" ] || dpkg-divert --local --rename --add /sbin/initctl && ln -sf /bin/true /sbin/initctl
ENV DEBIAN_FRONTEND noninteractive
ENV container docker
RUN apt-get update
RUN apt-get install -y sudo openssh-server curl lsb-release
RUN if ! getent passwd kitchen; then \
      useradd -d /home/kitchen -m -s /bin/bash -p '*' kitchen; \
    fi
RUN echo "kitchen ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo "Defaults !requiretty" >> /etc/sudoers
RUN mkdir -p /home/kitchen/.ssh
RUN chown -R kitchen /home/kitchen/.ssh
RUN chmod 0700 /home/kitchen/.ssh
RUN touch /home/kitchen/.ssh/authorized_keys
RUN chown kitchen /home/kitchen/.ssh/authorized_keys
RUN chmod 0600 /home/kitchen/.ssh/authorized_keys
RUN echo ssh-rsa <key> kitchen_docker_key >> /home/kitchen/.ssh/authorized_keys
```

### Scenario:

I am attempted to use `mysql_service`, but it looks for `/sbin/status`, which doesn't exist.  So, I tried to use an alternative provider as per instructions to see if it works better, with `Chef::Provider::MysqlServiceSysvinit`

### Steps to Reproduce:

Simple Cookbook the following default.rb:

```ruby
apt_update 'Update the apt cache daily' do
  frequency 86_400
  action :periodic
end

mysql_service 'default' do
  version '5.7'
  bind_address '0.0.0.0'
  port '3306'
  data_dir '/data'
  initial_root_password 'sekret'
  provider Chef::Provider::MysqlServiceSysvinit
  action [:create, :start]
end
```
Utilize TestKitchen to bootstrap the environment:

```
---
driver:
  name: docker

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || "auto" %>

verifier:
  name: inspec
  sudo: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[ez_mysql::default]
    verifier:
      inspec_tests:
        - test/integration/default
      attributes:
        service_type: sysv
    attributes:
```

My metadata.rb includes the cookbook:

```ruby
depends 'mysql', '~> 8.5.1'
depends 'mysql2_chef_gem', '~> 2.1.0'
depends 'database', '~> 6.1.1'
```

Steps

1. Generate a cookbook, e.g. `chef generate cookbook ez_mysql`, and update `recipes/default.rb`, `.kitchen.yml`, and `metadata.rb`
1. `kitchen create`
2. `kitchen converge`

### Expected Result:

Following the instructions in README.md on changing the default provider, such as using `Chef::Provider::MysqlServiceSysvinit`, it would work.  If I need to include something to get at the constant, that should be in the instructions as well.

### Actual Result:

I put the install part in install.rb, default.rb has `include_recipe 'ez_mysql::install'`.  When I reference `Chef::Provider::MysqlServiceSysvinit`, get uninitialized constant.  Not sure what to do.

```
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/ez_mysql/recipes/default.rb
       ================================================================================

       NameError
       ---------
       uninitialized constant Chef::Provider::MysqlServiceSysvinit

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/ez_mysql/recipes/install.rb:22:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/ez_mysql/recipes/install.rb:16:in `from_file'
         /tmp/kitchen/cache/cookbooks/ez_mysql/recipes/default.rb:8:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/ez_mysql/recipes/install.rb:

        15:
        16:  mysql_service 'default' do
        17:    version '5.7'
        18:    bind_address '0.0.0.0'
        19:    port '3306'
        20:    data_dir '/data'
        21:    initial_root_password node['ez_mysql']['database']['root_password']
        22>>   provider Chef::Provider::MysqlServiceSysvinit
        23:    action [:create, :start]
        24:  end
        25:
        26:

       System Info:
       ------------
       chef_version=14.6.47
       platform=ubuntu
       platform_version=16.04
       ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
       program_name=/opt/chef/bin/chef-client
       executable=/opt/chef/bin/chef-client
```

**Comment by joseluis-fw** [comment]
@darkn3rd README is wrong, you need to make this change:

```
-  provider Chef::Provider::MysqlServiceSysvinit
+  service_manager 'sysvinit'
```
